// Sample deals for a development database: the invented dataset the prototypes used.
// Brands and prices are made up. Store names are plain text labels only.
import type { Category, Store } from '../worker/db/taxonomy.ts'

type Row = [
  title: string,
  brand: string,
  store: Store,
  place: [prefecture: string, city: string] | null,
  originalPrice: number,
  salePrice: number,
  endsInHours: number,
  postedHoursAgo: number,
  rating: number,
  reviews: number,
  blurb: string,
]

const AKIBA: [string, string] = ['Tokyo', 'Chiyoda']
const SHINJUKU: [string, string] = ['Tokyo', 'Shinjuku']
const UMEDA: [string, string] = ['Osaka', 'Osaka']
const YOKOHAMA: [string, string] = ['Kanagawa', 'Yokohama']
const HAKATA: [string, string] = ['Fukuoka', 'Fukuoka']
const SAPPORO: [string, string] = ['Hokkaido', 'Sapporo']
const KYOTO: [string, string] = ['Kyoto', 'Kyoto']
const NAGOYA: [string, string] = ['Aichi', 'Nagoya']
const SENDAI: [string, string] = ['Miyagi', 'Sendai']

const rows: Record<Category, Row[]> = {
  Shoes: [
    [
      'Cloudstep Pastel Runner',
      'Hayate',
      'Rakuten',
      null,
      14800,
      8880,
      30,
      3,
      4.6,
      1284,
      'Lightweight daily runner with a cushioned midsole.',
    ],
    [
      'Court Classic Low White',
      'Tsubame',
      'Amazon',
      null,
      11000,
      7150,
      96,
      20,
      4.4,
      932,
      'Leather court sneaker that goes with everything.',
    ],
    [
      'Trail Blaze 2 Orange',
      'Hayate',
      'Yodobashi',
      SHINJUKU,
      16500,
      9900,
      52,
      8,
      4.5,
      411,
      'Grippy outsole for wet pavements and light trails.',
    ],
    [
      'Aero Knit Slip-on',
      'Kumo',
      'Rakuten',
      null,
      9800,
      3920,
      12,
      1,
      4.2,
      2210,
      'Breathable knit upper, folds flat for travel.',
    ],
    [
      'Flight Mid Retro',
      'Tsubame',
      'Amazon',
      null,
      19800,
      15840,
      160,
      40,
      4.7,
      356,
      'Retro basketball silhouette in a limited colourway.',
    ],
  ],
  Clothing: [
    [
      'Rider Leather Jacket',
      'Mori',
      'Rakuten',
      null,
      42000,
      25200,
      72,
      14,
      4.5,
      188,
      'Full-grain leather with a quilted lining.',
    ],
    [
      'Field Chore Coat',
      'Mori',
      'Amazon',
      null,
      18700,
      13090,
      120,
      30,
      4.3,
      264,
      'Heavy cotton twill coat with four patch pockets.',
    ],
    [
      'Everyday Oxford Shirt 3-pack',
      'Nami',
      'Rakuten',
      null,
      8970,
      4480,
      20,
      5,
      4.1,
      1510,
      'Wrinkle-resistant oxford shirts in three colours.',
    ],
    [
      'Sunset Zip Hoodie',
      'Kumo',
      'Yodobashi',
      UMEDA,
      7900,
      3950,
      40,
      6,
      4.4,
      702,
      'Brushed fleece hoodie, relaxed fit.',
    ],
    [
      'Canvas Work Jacket',
      'Mori',
      'Amazon',
      null,
      15400,
      11550,
      200,
      55,
      4.6,
      97,
      'Waxed canvas with a corduroy collar.',
    ],
  ],
  Audio: [
    [
      'Studio One Wireless Headphones',
      'Akari',
      'Yodobashi',
      AKIBA,
      38500,
      23100,
      28,
      2,
      4.7,
      3420,
      'Noise cancelling over-ears with 40-hour battery.',
    ],
    [
      'Pulse ANC Over-ear',
      'Sora',
      'Amazon',
      null,
      29800,
      19370,
      84,
      18,
      4.5,
      2107,
      'Adaptive noise cancelling and multipoint Bluetooth.',
    ],
    [
      'Desk Monitor Headphones',
      'Akari',
      'Rakuten',
      null,
      16800,
      11760,
      144,
      36,
      4.4,
      588,
      'Closed-back monitors tuned for mixing.',
    ],
    [
      'Blossom Wireless On-ear',
      'Sora',
      'Rakuten',
      null,
      12800,
      6400,
      10,
      1,
      4.2,
      1345,
      'Light on-ear headphones in pastel pink.',
    ],
    [
      'Reference 50 Wired',
      'Akari',
      'Yodobashi',
      null,
      24200,
      16940,
      60,
      12,
      4.8,
      276,
      'Open, detailed sound with a detachable cable.',
    ],
  ],
  Cameras: [
    [
      'Alpha Frame Mirrorless Body',
      'Hoshi',
      'Yodobashi',
      AKIBA,
      248000,
      198400,
      48,
      9,
      4.8,
      512,
      'Full-frame 33MP body with in-body stabilisation.',
    ],
    [
      'Rebel Starter DSLR Kit',
      'Ishi',
      'Amazon',
      null,
      89800,
      62860,
      110,
      26,
      4.4,
      1890,
      'Beginner DSLR with an 18-55mm kit lens.',
    ],
    [
      'Prime 50mm f/1.8 Lens',
      'Ishi',
      'Rakuten',
      null,
      32000,
      22400,
      36,
      7,
      4.7,
      2644,
      'Fast standard prime for portraits and low light.',
    ],
    [
      'Travel Zoom Compact',
      'Hoshi',
      'Yodobashi',
      YOKOHAMA,
      64800,
      45360,
      22,
      4,
      4.3,
      431,
      'Pocketable 30x zoom with a tilting screen.',
    ],
    [
      'Creator Vlog Camera Set',
      'Hoshi',
      'Amazon',
      null,
      118000,
      94400,
      180,
      48,
      4.5,
      263,
      'Vlog camera bundled with grip and microphone.',
    ],
  ],
  Computers: [
    [
      'Slimbook 14 Laptop 16GB/512GB',
      'Kaze',
      'Amazon',
      null,
      168000,
      126000,
      66,
      11,
      4.6,
      874,
      '1.2kg aluminium laptop with an all-day battery.',
    ],
    [
      'Airlite 13 Laptop 8GB/256GB',
      'Kaze',
      'Yodobashi',
      SHINJUKU,
      124800,
      99840,
      34,
      5,
      4.5,
      1203,
      'Fanless 13-inch laptop for study and travel.',
    ],
    [
      'Pro Studio 16 Laptop 32GB/1TB',
      'Sora',
      'Rakuten',
      null,
      328000,
      262400,
      130,
      33,
      4.8,
      219,
      'Creator laptop with a mini-LED display.',
    ],
    [
      'Workmate 15 Business Laptop',
      'Ishi',
      'Amazon',
      null,
      98000,
      58800,
      16,
      2,
      4.1,
      645,
      'Reliable office laptop with a numeric keypad.',
    ],
    [
      'Silver Edge 14 OLED',
      'Kaze',
      'Yodobashi',
      UMEDA,
      189800,
      142350,
      90,
      22,
      4.7,
      398,
      'OLED screen and a 120Hz refresh rate.',
    ],
  ],
  Watches: [
    [
      'Meridian Automatic 40mm',
      'Toki',
      'Rakuten',
      null,
      54000,
      35100,
      75,
      15,
      4.6,
      322,
      'Automatic movement with a sapphire crystal.',
    ],
    [
      'Minimal Mesh Quartz',
      'Toki',
      'Amazon',
      null,
      16500,
      8250,
      26,
      3,
      4.3,
      1876,
      'Slim case and a Milanese mesh strap.',
    ],
    [
      'Navigator Chronograph',
      'Hoshi',
      'Yodobashi',
      NAGOYA,
      68000,
      47600,
      44,
      10,
      4.5,
      154,
      'Steel chronograph, water resistant to 100m.',
    ],
    [
      'Stealth Chrono Black',
      'Toki',
      'Amazon',
      null,
      39800,
      27860,
      150,
      38,
      4.4,
      506,
      'All-black case with luminous hands.',
    ],
    [
      'Heritage Two-tone',
      'Hoshi',
      'Rakuten',
      null,
      82000,
      65600,
      210,
      60,
      4.7,
      88,
      'Two-tone bracelet watch with a date window.',
    ],
  ],
  Appliances: [
    [
      'Barista Drip Coffee Maker',
      'Yuki',
      'Yodobashi',
      KYOTO,
      19800,
      11880,
      38,
      6,
      4.4,
      967,
      'Programmable drip brewer with a thermal carafe.',
    ],
    [
      'Espresso Pro Machine',
      'Yuki',
      'Amazon',
      null,
      74800,
      52360,
      100,
      24,
      4.6,
      438,
      '15-bar pump with a steam wand.',
    ],
    [
      'Compact Espresso Maker',
      'Kaze',
      'Rakuten',
      null,
      29800,
      13410,
      14,
      1,
      4.2,
      1532,
      'Small-footprint espresso maker for one or two cups.',
    ],
    [
      'Capsule Coffee Machine',
      'Yuki',
      'Amazon',
      null,
      12800,
      8960,
      58,
      13,
      4.3,
      2890,
      'One-touch capsule machine, heats in 25 seconds.',
    ],
    [
      'Counter Bean-to-cup',
      'Yuki',
      'Yodobashi',
      HAKATA,
      98000,
      73500,
      170,
      44,
      4.7,
      205,
      'Built-in grinder with five drink presets.',
    ],
  ],
  Beauty: [
    [
      'Rose Glow Skincare Set',
      'Hana',
      'Rakuten',
      null,
      9800,
      5880,
      24,
      4,
      4.5,
      3104,
      'Five-piece set: cleanser, toner, serum, cream, mask.',
    ],
    [
      'Colour Palette Makeup Kit',
      'Hana',
      'Amazon',
      null,
      6800,
      4080,
      80,
      19,
      4.2,
      1422,
      'Eyeshadow, blush and lip colours in one kit.',
    ],
    [
      'Vitamin C Serum 30ml',
      'Shizuku',
      'Rakuten',
      null,
      4800,
      2160,
      8,
      1,
      4.6,
      5210,
      'Brightening serum with 15% vitamin C.',
    ],
    [
      'Daily Defence Sunscreen Duo',
      'Shizuku',
      'Yodobashi',
      null,
      3960,
      2970,
      115,
      28,
      4.4,
      2033,
      'SPF50+ PA++++ in a two-bottle pack.',
    ],
    [
      'Repair Night Cream',
      'Hana',
      'Amazon',
      null,
      7200,
      5040,
      140,
      35,
      4.3,
      876,
      'Ceramide cream for dry and sensitive skin.',
    ],
  ],
  Bags: [
    [
      'Metro Daypack 20L',
      'Kumo',
      'Amazon',
      null,
      13200,
      7920,
      46,
      8,
      4.5,
      2256,
      'Water-repellent daypack with a laptop sleeve.',
    ],
    [
      'Crimson Leather Backpack',
      'Mori',
      'Rakuten',
      null,
      28600,
      17160,
      92,
      21,
      4.4,
      318,
      'Soft leather backpack with brass hardware.',
    ],
    [
      'Heritage Leather Rucksack',
      'Mori',
      'Yodobashi',
      YOKOHAMA,
      34100,
      23870,
      62,
      12,
      4.6,
      142,
      'Vegetable-tanned leather that ages well.',
    ],
    [
      'Summit Hiking Pack 35L',
      'Hayate',
      'Amazon',
      null,
      22000,
      13200,
      18,
      2,
      4.7,
      689,
      'Ventilated back panel and a rain cover.',
    ],
    [
      'Studio Black Backpack',
      'Kumo',
      'Rakuten',
      null,
      18700,
      14960,
      190,
      50,
      4.3,
      254,
      'Minimal backpack with a hidden pocket.',
    ],
  ],
  Kitchen: [
    [
      'Tri-ply Saucepan Set 3pc',
      'Tetsu',
      'Amazon',
      null,
      19800,
      12870,
      54,
      10,
      4.5,
      734,
      'Three stainless saucepans, induction compatible.',
    ],
    [
      'Indigo Dinnerware 16pc',
      'Nami',
      'Rakuten',
      null,
      12400,
      6200,
      32,
      5,
      4.4,
      1198,
      'Glazed stoneware set for four.',
    ],
    [
      'Enamel Casserole 24cm',
      'Tetsu',
      'Yodobashi',
      SAPPORO,
      24200,
      16940,
      78,
      17,
      4.8,
      492,
      'Cast-iron casserole in red enamel.',
    ],
    [
      'Stainless Stockpot Trio',
      'Tetsu',
      'Amazon',
      null,
      15800,
      11060,
      125,
      31,
      4.3,
      367,
      'Three stockpots with glass lids.',
    ],
    [
      'Open Shelf Cookware Set 10pc',
      'Nami',
      'Rakuten',
      null,
      29800,
      20860,
      220,
      58,
      4.6,
      173,
      'Non-stick cookware set with utensils.',
    ],
  ],
  Gaming: [
    [
      'Neon Wireless Controller',
      'Raijin',
      'Yodobashi',
      AKIBA,
      8980,
      5390,
      21,
      2,
      4.5,
      4120,
      'Hall-effect sticks and a 30-hour battery.',
    ],
    [
      'Arctic White Gamepad',
      'Raijin',
      'Amazon',
      null,
      7480,
      5240,
      70,
      16,
      4.4,
      2988,
      'Wireless gamepad with motion controls.',
    ],
    [
      'Pro Paddle Controller',
      'Raijin',
      'Rakuten',
      null,
      22800,
      15960,
      105,
      25,
      4.6,
      615,
      'Four back paddles and swappable sticks.',
    ],
    [
      'Midnight Gamepad v2',
      'Sora',
      'Amazon',
      null,
      6980,
      2980,
      9,
      1,
      4.1,
      1877,
      'Budget wired controller with turbo mode.',
    ],
    [
      'Charging Dock + Controller Bundle',
      'Raijin',
      'Yodobashi',
      SENDAI,
      12800,
      9600,
      135,
      34,
      4.5,
      341,
      'Controller with a two-slot charging dock.',
    ],
  ],
  Furniture: [
    [
      'Shell Dining Chair',
      'Kigi',
      'Rakuten',
      null,
      16800,
      10080,
      86,
      20,
      4.5,
      528,
      'Moulded seat on solid beech legs.',
    ],
    [
      'Lounge Armchair Blue',
      'Kigi',
      'Amazon',
      null,
      39800,
      23880,
      42,
      7,
      4.3,
      211,
      'Deep-seat armchair in woven fabric.',
    ],
    [
      'Ergo Task Chair',
      'Kaze',
      'Yodobashi',
      SHINJUKU,
      48000,
      33600,
      56,
      11,
      4.7,
      1466,
      'Adjustable lumbar support and a mesh back.',
    ],
    [
      'Oak Side Chair',
      'Kigi',
      'Rakuten',
      null,
      21000,
      14700,
      165,
      42,
      4.6,
      134,
      'Solid oak chair with a paper-cord seat.',
    ],
    [
      'Ash Stacking Chair 2-pack',
      'Kigi',
      'Amazon',
      null,
      27600,
      22080,
      230,
      62,
      4.4,
      96,
      'Two stackable chairs in natural ash.',
    ],
  ],
}

const slug = (s: string) =>
  s
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-|-$/g, '')

const STORE_URLS: Record<Store, string> = {
  Yodobashi: 'https://www.yodobashi.com/',
  Rakuten: 'https://www.rakuten.co.jp/',
  Amazon: 'https://www.amazon.co.jp/',
}

export const sampleDeals = (Object.keys(rows) as Category[]).flatMap((category) =>
  rows[category].map(
    (
      [
        title,
        brand,
        store,
        place,
        originalPrice,
        salePrice,
        endsInHours,
        postedHoursAgo,
        rating,
        reviews,
        blurb,
      ],
      i,
    ) => ({
      id: slug(title),
      title,
      brand,
      category,
      store,
      channel: place ? 'in-store' : 'online',
      prefecture: place?.[0] ?? null,
      city: place?.[1] ?? null,
      originalPrice,
      salePrice,
      endsInHours,
      postedHoursAgo,
      rating,
      reviews,
      image: `/images/${category.toLowerCase()}-${i + 1}.jpg`,
      // The sample products do not exist, so the link goes to the store's front page.
      url: STORE_URLS[store],
      blurb,
    }),
  ),
)
